Warning: no access to tty (Bad file descriptor).
Thus no job control in this shell.
python3 -u train_adversary.py --nodes 200 --budget 6 --graph-type erdos_renyi --graph-pool-nbr 1 --train-graph-nbr 1 --valid-graph-nbr 1 --valid-with-nature False --edge-p 0.05 --main-method rl --train-episodes 3000 --valid-episodes 3 --rl-algor DDQN --buffer-type er --nnVersion v01 --batch-size 16 --GAT-heads 8 --GAT-atten-layer 1 --GAT-out-atten-layer 2 --GAT-hid-dim '(8,)' --GAT-s-hid-dim '(8,)' --GAT-out-hid-dim '(32,1)' --GAT-s-out-hid-dim '(32,1)' --alpha 0.2 --use-decay 0 --init-epsilon 0.99 --final-epsilon 0.01 --epsilon-decay-steps 2000 --logdir 10_14 --logtime 1106 --seed-nbr 1 --gamma 0.99 --lr 1e-2 >../pscr/log_5/10_14/logdir/1106.txt 2>../pscr/log_5/10_14/logdir/1106_error.txt &
